// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjo7d9UxDoIjVjphzof-ZLbw2mINCUFpQ',
    appId: '1:836383345512:web:5b9bf3bafe8f4e726c64dd',
    messagingSenderId: '836383345512',
    projectId: 'bus-saathi',
    authDomain: 'bus-saathi.firebaseapp.com',
    storageBucket: 'bus-saathi.appspot.com',
    measurementId: 'G-P28J3LPHYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrtabgkpQdFEAo9jWgGqmxdf2N2k-NhUA',
    appId: '1:836383345512:android:4c014d149e39bc6f6c64dd',
    messagingSenderId: '836383345512',
    projectId: 'bus-saathi',
    storageBucket: 'bus-saathi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFtnTUnB-bQyvIkxECeoqPLcPZQzUgGXk',
    appId: '1:836383345512:ios:3ff033816731b9bd6c64dd',
    messagingSenderId: '836383345512',
    projectId: 'bus-saathi',
    storageBucket: 'bus-saathi.appspot.com',
    iosBundleId: 'com.example.busSaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFtnTUnB-bQyvIkxECeoqPLcPZQzUgGXk',
    appId: '1:836383345512:ios:1f97bae8be48b9ab6c64dd',
    messagingSenderId: '836383345512',
    projectId: 'bus-saathi',
    storageBucket: 'bus-saathi.appspot.com',
    iosBundleId: 'com.example.busSaathi.RunnerTests',
  );
}
